// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: natsSubjects.proto

package subjects

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Subject int32

const (
	Subject_UNKNOWN_SUBJECT Subject = 0
	Subject_TICKET_CREATED  Subject = 1
	Subject_TICKET_UPDATED  Subject = 2
	Subject_ORDER_CREATED   Subject = 3
	Subject_ORDER_CANCELLED Subject = 4
)

// Enum value maps for Subject.
var (
	Subject_name = map[int32]string{
		0: "UNKNOWN_SUBJECT",
		1: "TICKET_CREATED",
		2: "TICKET_UPDATED",
		3: "ORDER_CREATED",
		4: "ORDER_CANCELLED",
	}
	Subject_value = map[string]int32{
		"UNKNOWN_SUBJECT": 0,
		"TICKET_CREATED":  1,
		"TICKET_UPDATED":  2,
		"ORDER_CREATED":   3,
		"ORDER_CANCELLED": 4,
	}
)

func (x Subject) Enum() *Subject {
	p := new(Subject)
	*p = x
	return p
}

func (x Subject) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Subject) Descriptor() protoreflect.EnumDescriptor {
	return file_natsSubjects_proto_enumTypes[0].Descriptor()
}

func (Subject) Type() protoreflect.EnumType {
	return &file_natsSubjects_proto_enumTypes[0]
}

func (x Subject) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Subject.Descriptor instead.
func (Subject) EnumDescriptor() ([]byte, []int) {
	return file_natsSubjects_proto_rawDescGZIP(), []int{0}
}

var File_natsSubjects_proto protoreflect.FileDescriptor

var file_natsSubjects_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6e, 0x61, 0x74, 0x73, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x6e, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x13, 0x0a, 0x0f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x53, 0x55, 0x42, 0x4a, 0x45,
	0x43, 0x54, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x49, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x43,
	0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x49, 0x43, 0x4b,
	0x45, 0x54, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d,
	0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12,
	0x13, 0x0a, 0x0f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c,
	0x45, 0x44, 0x10, 0x04, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x6c, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x77,
	0x6e, 0x2d, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x61, 0x70, 0x70, 0x2d, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_natsSubjects_proto_rawDescOnce sync.Once
	file_natsSubjects_proto_rawDescData = file_natsSubjects_proto_rawDesc
)

func file_natsSubjects_proto_rawDescGZIP() []byte {
	file_natsSubjects_proto_rawDescOnce.Do(func() {
		file_natsSubjects_proto_rawDescData = protoimpl.X.CompressGZIP(file_natsSubjects_proto_rawDescData)
	})
	return file_natsSubjects_proto_rawDescData
}

var file_natsSubjects_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_natsSubjects_proto_goTypes = []interface{}{
	(Subject)(0), // 0: Subject
}
var file_natsSubjects_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_natsSubjects_proto_init() }
func file_natsSubjects_proto_init() {
	if File_natsSubjects_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_natsSubjects_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_natsSubjects_proto_goTypes,
		DependencyIndexes: file_natsSubjects_proto_depIdxs,
		EnumInfos:         file_natsSubjects_proto_enumTypes,
	}.Build()
	File_natsSubjects_proto = out.File
	file_natsSubjects_proto_rawDesc = nil
	file_natsSubjects_proto_goTypes = nil
	file_natsSubjects_proto_depIdxs = nil
}
