// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: orderCancelled.proto

package events

import (
	subjects "github.com/basilnsage/mwn-ticketapp-common/subjects"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OrderCancelled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject subjects.Subject `protobuf:"varint,1,opt,name=subject,proto3,enum=Subject" json:"subject,omitempty"`
	Data    *CancelledData   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *OrderCancelled) Reset() {
	*x = OrderCancelled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderCancelled_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelled) ProtoMessage() {}

func (x *OrderCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_orderCancelled_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelled.ProtoReflect.Descriptor instead.
func (*OrderCancelled) Descriptor() ([]byte, []int) {
	return file_orderCancelled_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCancelled) GetSubject() subjects.Subject {
	if x != nil {
		return x.Subject
	}
	return subjects.Subject_UNKNOWN_SUBJECT
}

func (x *OrderCancelled) GetData() *CancelledData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CancelledData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ticket *CancelledData_Ticket `protobuf:"bytes,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
}

func (x *CancelledData) Reset() {
	*x = CancelledData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderCancelled_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelledData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelledData) ProtoMessage() {}

func (x *CancelledData) ProtoReflect() protoreflect.Message {
	mi := &file_orderCancelled_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelledData.ProtoReflect.Descriptor instead.
func (*CancelledData) Descriptor() ([]byte, []int) {
	return file_orderCancelled_proto_rawDescGZIP(), []int{1}
}

func (x *CancelledData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelledData) GetTicket() *CancelledData_Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type CancelledData_Ticket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CancelledData_Ticket) Reset() {
	*x = CancelledData_Ticket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderCancelled_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelledData_Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelledData_Ticket) ProtoMessage() {}

func (x *CancelledData_Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_orderCancelled_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelledData_Ticket.ProtoReflect.Descriptor instead.
func (*CancelledData_Ticket) Descriptor() ([]byte, []int) {
	return file_orderCancelled_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CancelledData_Ticket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_orderCancelled_proto protoreflect.FileDescriptor

var file_orderCancelled_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x6e, 0x61, 0x74, 0x73, 0x53, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x0e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x07,
	0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e,
	0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x68, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65,
	0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65,
	0x64, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x74, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x1a, 0x18, 0x0a, 0x06, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x42, 0x33,
	0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x73,
	0x69, 0x6c, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x77, 0x6e, 0x2d, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x61, 0x70, 0x70, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orderCancelled_proto_rawDescOnce sync.Once
	file_orderCancelled_proto_rawDescData = file_orderCancelled_proto_rawDesc
)

func file_orderCancelled_proto_rawDescGZIP() []byte {
	file_orderCancelled_proto_rawDescOnce.Do(func() {
		file_orderCancelled_proto_rawDescData = protoimpl.X.CompressGZIP(file_orderCancelled_proto_rawDescData)
	})
	return file_orderCancelled_proto_rawDescData
}

var file_orderCancelled_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_orderCancelled_proto_goTypes = []interface{}{
	(*OrderCancelled)(nil),       // 0: OrderCancelled
	(*CancelledData)(nil),        // 1: CancelledData
	(*CancelledData_Ticket)(nil), // 2: CancelledData.Ticket
	(subjects.Subject)(0),        // 3: Subject
}
var file_orderCancelled_proto_depIdxs = []int32{
	3, // 0: OrderCancelled.subject:type_name -> Subject
	1, // 1: OrderCancelled.data:type_name -> CancelledData
	2, // 2: CancelledData.ticket:type_name -> CancelledData.Ticket
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_orderCancelled_proto_init() }
func file_orderCancelled_proto_init() {
	if File_orderCancelled_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orderCancelled_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCancelled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderCancelled_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelledData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderCancelled_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelledData_Ticket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orderCancelled_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orderCancelled_proto_goTypes,
		DependencyIndexes: file_orderCancelled_proto_depIdxs,
		MessageInfos:      file_orderCancelled_proto_msgTypes,
	}.Build()
	File_orderCancelled_proto = out.File
	file_orderCancelled_proto_rawDesc = nil
	file_orderCancelled_proto_goTypes = nil
	file_orderCancelled_proto_depIdxs = nil
}
